'use client';

import { useCrmStore } from '@/store/crmStore';
import { Briefcase, Target, TrendingUp, AlertTriangle, DollarSign, Search, Zap } from 'lucide-react';
import { useState } from 'react';

export function BrokerIntelligence() {
  const { brokers } = useCrmStore();
  const [searchQuery, setSearchQuery] = useState('');

  // Enhance broker data with AI mock fields
  const intelligenceBrokers = brokers.map(b => {
    const churnRisk = b.dealsClosed === 0 ? 'HIGH' : b.revenueGenerated > 10000000 ? 'LOW' : 'MEDIUM';
    const futureRevenue = b.revenueGenerated * 1.2; // Mock AI prediction
    const growthPotential = b.conversionRate > 3 ? 'HIGH' : 'MODERATE';
    return { ...b, churnRisk, futureRevenue, growthPotential };
  });

  const filteredBrokers = intelligenceBrokers.filter(b => b.name.toLowerCase().includes(searchQuery.toLowerCase()) || b.company.toLowerCase().includes(searchQuery.toLowerCase()));

  const totalNetworkRevenue = brokers.reduce((acc, b) => acc + b.revenueGenerated, 0);

  return (
    <div className="p-8 h-full overflow-y-auto">
      
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-medium text-white tracking-wide">Broker & Network Intelligence</h1>
          <p className="text-neutral-500 mt-2">Predictive analytics for channel partners, identifying churn risk and growth potential.</p>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-4 mb-8">
        <div className="bg-[#121212] border border-neutral-800 rounded-xl p-5 relative overflow-hidden">
          <div className="flex items-center gap-2 text-neutral-400 mb-3">
            <DollarSign className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Network Revenue</span>
          </div>
          <div className="text-3xl font-medium text-green-400 mb-1">${(totalNetworkRevenue / 1000000).toFixed(1)}M</div>
          <div className="text-xs text-neutral-500 mt-2">Generated by external partners</div>
        </div>

        <div className="bg-[#121212] border border-neutral-800 rounded-xl p-5 relative overflow-hidden">
          <div className="flex items-center gap-2 text-[#00E5FF] mb-3">
            <TrendingUp className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Predicted Q3 Rev.</span>
          </div>
          <div className="text-3xl font-medium text-white mb-1">${(totalNetworkRevenue * 1.15 / 1000000).toFixed(1)}M</div>
          <div className="text-xs text-green-400 mt-2">+15% expected growth</div>
        </div>

        <div className="bg-[#121212] border border-neutral-800 rounded-xl p-5 relative overflow-hidden">
          <div className="flex items-center gap-2 text-amber-400 mb-3">
            <AlertTriangle className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Churn Risk Network</span>
          </div>
          <div className="text-3xl font-medium text-white mb-1">12%</div>
          <div className="text-xs text-neutral-500 mt-2">Partners inactive > 90 days</div>
        </div>

        <div className="bg-[#121212] border border-neutral-800 rounded-xl p-5 relative overflow-hidden">
          <div className="flex items-center gap-2 text-purple-400 mb-3">
            <Zap className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">High Potential Partners</span>
          </div>
          <div className="text-3xl font-medium text-white mb-1">8</div>
          <div className="text-xs text-neutral-500 mt-2">Ready for exclusive allocation</div>
        </div>
      </div>

      <div className="flex items-center justify-between mb-4">
        <h3 className="text-sm font-bold text-neutral-400 uppercase tracking-widest">Partner AI Diagnostic Matrix</h3>
        <div className="relative">
          <Search className="w-4 h-4 text-neutral-500 absolute left-3 top-1/2 -translate-y-1/2" />
          <input 
            type="text" 
            placeholder="Search partners..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-64 h-9 bg-[#121212] border border-neutral-800 rounded pl-9 pr-4 text-sm text-white placeholder-neutral-500 focus:outline-none focus:border-[#00E5FF]"
          />
        </div>
      </div>

      <div className="bg-[#121212] border border-neutral-800 rounded-xl overflow-hidden flex flex-col mb-8">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left whitespace-nowrap">
            <thead className="bg-[#1A1C20] border-b border-neutral-800">
              <tr className="text-[10px] font-bold text-neutral-500 uppercase tracking-widest">
                <th className="px-6 py-4 font-medium">PARTNER</th>
                <th className="px-6 py-4 font-medium text-right">HISTORICAL REVENUE</th>
                <th className="px-6 py-4 font-medium text-right">PREDICTED REVENUE (Q3)</th>
                <th className="px-6 py-4 font-medium text-center">GROWTH POTENTIAL</th>
                <th className="px-6 py-4 font-medium text-center">CHURN RISK</th>
                <th className="px-6 py-4 font-medium w-64">AI RECOMMENDATION</th>
              </tr>
            </thead>
            <tbody>
              {filteredBrokers.map((broker) => (
                <tr key={broker.id} className="border-b border-neutral-800/50 hover:bg-[#1A1C20] transition-colors">
                  <td className="px-6 py-4">
                    <div className="font-medium text-white">{broker.name}</div>
                    <div className="text-[10px] text-neutral-500 mt-0.5">{broker.company}</div>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="text-white font-medium">${(broker.revenueGenerated / 1000000).toFixed(2)}M</div>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <div className="text-[#00E5FF] font-medium">${(broker.futureRevenue / 1000000).toFixed(2)}M</div>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className={`px-2.5 py-1 text-[10px] font-bold tracking-widest uppercase rounded border ${
                      broker.growthPotential === 'HIGH' ? 'bg-purple-500/10 text-purple-400 border-purple-500/20' :
                      'bg-neutral-800 text-neutral-400 border-neutral-700'
                    }`}>
                      {broker.growthPotential}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className={`px-2.5 py-1 text-[10px] font-bold tracking-widest uppercase rounded border ${
                      broker.churnRisk === 'LOW' ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                      broker.churnRisk === 'HIGH' ? 'bg-red-500/10 text-red-400 border-red-500/20' :
                      'bg-amber-500/10 text-amber-400 border-amber-500/20'
                    }`}>
                      {broker.churnRisk}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    {broker.growthPotential === 'HIGH' && broker.churnRisk === 'LOW' && (
                       <span className="text-xs text-green-400">Offer 0.5% bonus to lock in Q3 loyalty.</span>
                    )}
                    {broker.churnRisk === 'HIGH' && (
                       <span className="text-xs text-red-400">Assign relationship manager immediately.</span>
                    )}
                    {broker.churnRisk === 'MEDIUM' && broker.growthPotential === 'MODERATE' && (
                       <span className="text-xs text-neutral-400">Invite to upcoming broker networking event.</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
